services:
  postgres:
    image: postgres:16-alpine
    container_name: lala_store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lala_store
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/roles.sql:/docker-entrypoint-initdb.d/02-roles.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/03-seed.sql

volumes:
  postgres_data:
